name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export workflow traces to Tempo
        uses: corentinmusard/otel-cicd-action@v2
        with:
          otlpEndpoint: https://tempo-dev.o11y.web3factory.consensys.net/v1/traces
          otlpHeaders: "Authorization=Basic ${{ secrets.TEMPO_AUTH }}"
          otelServiceName: "gh-metrics-mobile"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
